os: osx
osx_image: xcode12.2  
language: swift
script: xcodebuild clean build test -project MVVM-Exercise/MVVM-Exercise.xcodeproj -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.2,name=iPhone 8 Plus" ONLY_ACTIVE_ARCH=N0 CODE_SIGNING_REQUIRED=NO
